Ghi chú ngày 2: học về pandas và eda
## Pandas 
- Pandas là thư viện python giúp đọc, lưu trữ, lọc, biến đổi, tổng hợp và phân tích dữ liệu dạng bảng, tương tự như excel nhưng có thể xử lý bằng code
=> Ví dụ: đọc file CSV chứa 100k đơn hàng, lọc đơn hàng lỗi, tính doanh thu theo tháng
## EDA - Exploratory Data Analysis
- Eda là quá trình phân tích khám phá dữ liệu nhằm hiểu dữ liệu có gì, phân phối ra sao, có bất thường không có những biến nào có thể liên quan đến nhau
=> Ví dụ: tìm hiểu vì sao doanh thu giảm, nhóm khách hàng nào mua nhiều nhất và sản phẩn nào bán chạy nhất

- Pandas thường được sử dụng để thực hiện EDA, kết với với các thư viện khác như numpy, matplotlib, seaborn

- 1 quy trình data science điển hình: thu thập dữ liệu => làm sạch dữ liệu => EDA => machine learning

In [9]:
import pandas as pd
print(pd.__version__)

3.0.6

In [10]:
pd.DataFrame ({'Yes' : [50,21], 'No' : [131,2]})

   Yes   No
0   50  131
1   21    2

In [11]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [ ]:
pd.Series([1,2,3,4,5])

In [13]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64